### PR TITLE
Don't register click when user moves away from Button before lifting finger

### PR DESCRIPTION
**Pull request by Seylox**

### CODE REVIEW

**Comment by lissy93** [comment]
+1 this PR. @StevenDXC any chance of a code review and merge?

**Comment by Seylox** [comment]
@Lissy93 if you want to use it with the Changes of the PR you can use it as a dependency from my Repo using Jitpack.io: https://jitpack.io/#Seylox/dxloadingbutton

**Comment by leoFengCT** [comment]
Touch Event did not add ACTION_CANCEL. It is not work well if touch and then move 

public boolean onTouchEvent(MotionEvent event) {
        if(!isEnabled()){
            return true;
        }
       Log.i("AAA","Action="+event.getAction()) ;
        switch (event.getAction()){
            case MotionEvent.ACTION_DOWN:
                mTouchX = event.getX();
                mTouchY = event.getY();
                playRippleAnimation(true,false);
                break;
            case MotionEvent.ACTION_UP:
                playRippleAnimation(false,false);
                break;
            case MotionEvent.ACTION_CANCEL:
                playRippleAnimation(false,true);
                break;
        }

        return true;
    }

**Comment by StevenDXC** [comment]
thanks, has merged @Seylox

**Pull request merged**
